### ISSUE TITLE
SDK_VERSION is not defined

### ISSUE THREAD

**Issue by asharma-r7** [okta/okta-signin-widget#100]
Version: 1.5.0

When issuing the request (submitting user input) from the widget the following error is emitted: `Uncaught ReferenceError: SDK_VERSION is not defined`

The widget has not been modified in anyway. 

Testing the widget initially using the Okta CDN package was issue free. I believe the CDN is using version 1.4.0 so I attempted to drop the version of the npm package to 1.4.0, however, the following occurs:

$npm install --save @okta/okta-signin-widget@1.4.0

```
npm WARN optional dep failed, continuing @okta/ci-update-package@1.4.0
npm WARN optional dep failed, continuing @okta/install-with-shrinkwrap@1.4.0
npm WARN optional dep failed, continuing @okta/ci-pkginfo@1.2.0
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/<user>/.nvm/v4.2.2/bin/node" "/Users/<user>/.nvm/v4.2.2/bin/npm" "install" "--save" "@okta/okta-signin-widget@1.4.0"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code E404

npm ERR! 404 Not found : @okta/i18n
npm ERR! 404
npm ERR! 404 '@okta/i18n' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@okta/okta-signin-widget'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```
I believe this is due to the @okta/i18n npm package not being publicly available as it is privately managed under the @okta org. 

It's also worth noting that the @okta/i18n is listed as an optional dependency in version 1.5.0 and doesn't fail when the package is not found. Thus listing both @okta/i18n and @okta/courage as optional dependencies would allow the package to successfully install. 

FYI: This can be considered to be two issues 1) SDK_VERSION is not defined 2) Unable to install v1.4.0

**Comment by lboyette-okta** [comment]
If I have this right, you're currently testing using the CDN, but you'd like to consume directly from npm instead. I'd recommend upgrading to the 1.5.0 version in the CDN first: https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/1.5.0/js/okta-sign-in.min.js, https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/1.5.0/css/okta-sign-in.min.css, https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/1.5.0/css/okta-theme.css.

As for the two issues:

1) The undefined SDK_VERSION was an issue when building 1.4.0, because of an issue in okta-auth-js. I'm unable to reproduce this when building 1.5.0 locally using webpack or when installing 1.5.0 from npm. If you're building locally, make sure you've pulled the latest, then `npm install` to ensure you have the latest node modules.

2) This is a known issue with 1.4.0 and the optionalDependencies solution in 1.5.0 is a workaround. This won't be an issue after npm [v2.15.10](https://github.com/npm/npm/releases/tag/v2.15.10) and [v3.10.7](https://github.com/npm/npm/releases/tag/v3.10.7) are released, because they allow scoped bundleDependencies. For now, use 1.5.0.

**Comment by asharma-r7** [comment]
Ok, I'll disregard v1.4.0. Might be worth updating the developer docs with the latest version - http://developer.okta.com/docs/guides/okta_sign-in_widget.html#creating-an-html-file-with-the-widget-code 

So after testing the v1.5.0 CDN I had no issues. I built v1.5.0 and sure enough it works as expected and the SDK_VERSION error no longer remains.

As you mentioned this error was found in v1.4.0 and the current state of the v1.5.0 npm module has not reflected the fix. I think a release with the latest changes is necessary for this to work out of the box. - would this be possible?

**Comment by lboyette-okta** [comment]
We pushed version 1.6.0 to npm today! This should fix your issues. You can review the release notes here: https://github.com/okta/okta-signin-widget/releases/tag/okta-signin-widget-1.6.0
