### ISSUE TITLE
Angular widget weird bug when session expires

### ISSUE THREAD

**Issue by TzlilSwimmer123** [okta/okta-signin-widget#1045]
### I'm submitting a
bug report

### Background info
I am using the widget for almost 3 months.
At the begging everything worked as expected.

On 09.02 we started seeing a weird bug.

When session expires and we try to go to our app, the widget is showing. After couple of milliseconds "login_required The client specified not to prompt, but the user is not logged in" logs to the console and than the page is redirected to:

{oktaDefaultDomain}/login/login.htm?fromURI=/oauth2/v1/authorize/redirect?okta_key={some key}

I am not sure what is going on...I do not have any configuration that suppose to redirect to that url.

Did not get any answers from customer care(It has been a week).

### Steps to reproduce

Go to app, login. close the tab. go to app again after a lot of time (when session expires). Than it happen, every time. If I refresh the page everything works fine.

### My environment
  - Okta Sign-In Widget Version: 3.7.0
  - okta-auth-js Version: 2.11.2
  - Browser: Chrome
  - Language: Angular

**Comment by swiftone** [comment]
@TzlilSwimmer123 - Sorry to hear you're having troubles.  Before we dig deeper, can I confirm:
- You're using the widget directly
- the widget is using authJS, but you're not using authJS directly
- you are using angular for your page, but you aren't using the Okta Angular SDK

Are these all true statements?

**Comment by TzlilSwimmer123** [comment]
Hi,

* You're using the widget directly - correct
* The widget is using authJS, but you're not using authJS directly - correct
* I am using "@okta/okta-angular": "^1.4.0" - that was specified in the tutorial also...(https://developer.okta.com/code/angular/okta_angular_sign-in_widget/)

Thanks

**Comment by teja123r** [comment]
Yes same thing is happening with me

**Comment by swiftone** [comment]
@TzlilSwimmer123 and @teja123r - 

It looks this is not the sign-in-widget, but rather the angular SDK.

The issue is that the when the user's Okta session expires, the user needs to re-authenticate (provide credentials).
(Previously your app would simply consider them no longer authenticated)

(If you are saying the users are UNABLE to revalidate, please let us know)

You can override the behavior that occurs when the session expires by setting the `onSessionExpired` callback here: https://github.com/okta/okta-oidc-js/tree/master/packages/okta-angular#okta_config

**Comment by teja123r** [comment]
overriding `onSessionExpired` helped. Thanks.

**Comment by TzlilSwimmer123** [comment]
Thanks, it also works for me

**Comment by pusherman** [comment]
@TzlilSwimmer123 or @teja123r  - I am having this same issue.  Can you explain what you overrode `onSessionExpired` with?

**Comment by TzlilSwimmer123** [comment]
Do you have an object that called "config" when you are defining the OKTA_CONFIG?

If so, just add:
onSessionExpired: () => {
  }
For example:

const config = {
  issuer: AppConstants.oktaDefaultDomain + '/oauth2/default',
  redirectUri: environment.oktaRedirectURL,
  clientId: environment.oktaAppClientID,
  pkce: true,
  onSessionExpired: () => {
  }
};

**Comment by pusherman** [comment]
Oh, just an empty function?  That didn't seem to help in my case. I still got the error.  Thanks for the response though!

**Comment by TzlilSwimmer123** [comment]
Can you post your code?
Maybe I will see the problem...

**Comment by pusherman** [comment]
I load the config from a service because the values are dynamically loaded at runtime but my OktaConfig is as follows

```
  const config = appSettingsService.getSettings();

  const oktaConfig: OktaConfig = {
    ...config.okta,
    scopes: ['openid', 'profile', 'email'],
    pkce: true,
    onSessionExpired: () => {
      localStorage.clear();
      location.reload();
    },
  };
```

Just an empty onSessionExpired function was still giving error messages in the console `"error.errorCode: login_required, error.description: The client specified not to prompt, but the user is not logged in.."` and the user can't re-auth until they clear their localStorage.  It seems as though the Okta library isn't automatically refreshing the token as it should.  At least with my work around above, the user is redirected to the login page instead of just getting the error and being stuck.
