### ISSUE TITLE
Widget CSS conflicts with my app

### ISSUE THREAD

**Issue by jfairley** [okta/okta-signin-widget#126]
I like that Okta provides this sign-in widget to help me get going, but the use of reset styles and other generic styles makes the provided CSS unusable

https://github.com/okta/okta-signin-widget/blob/okta-signin-widget-1.7.0/assets/sass/common/enduser/_reset.scss
https://github.com/okta/okta-signin-widget/blob/okta-signin-widget-1.7.0/assets/sass/widgets/_mega-drop-down.scss

Specifically, the global `input` styles and the generic `.dropdown` styles conflict with styles already built in my application, forcing me to completely style the Okta widget on my own. Something like this always needs to be scoped under an Okta class so as to not collide with everything else in your clients' custom apps.

**Comment by rchild-okta** [comment]
Definitely makes sense - it's something we can go ahead and fix in an upcoming release.

**Comment by lawrencetvo** [comment]
+1 important to one of my related projects.

**Comment by mraible** [comment]
I agree it'd be nice to have this fixed. Here's a new Angular app without the Sign In widget's CSS:

![screen shot 2017-03-14 at 1 07 27 pm](https://cloud.githubusercontent.com/assets/17892/23918301/0d1548e6-08b8-11e7-997a-745fe6dc38a5.png)

When I add the CSS, the `<h1>` that says "app works!" becomes much smaller and all the margins/padding go away.

![screen shot 2017-03-14 at 1 07 42 pm](https://cloud.githubusercontent.com/assets/17892/23918322/2575093a-08b8-11e7-9de5-70e3e28d3612.png)

**Comment by sasso** [comment]
Quick fix is to comment out 
```
//@import 'common/enduser/reset';
//@import 'base';
```
and build a release

**Comment by omgitstom** [comment]
This is a bug, not an enhancement

**Comment by pith** [comment]
Any plan on releasing this fix ? This widget is awesome but this bug makes it really annoying.

**Comment by AdrianZielonka** [comment]
+1. Any word on when this fix will be released? Our organisation has just purchased Okta and would like to utilisethe Sign In Widget, however it hijacks our entire SPAs CSS.

**Comment by omgitstom** [comment]
We are going to work on getting a release out for this issue this week, thanks for your patience!

**Comment by ericmcgregor** [comment]
I also am working on integrating Okta with some applications at my company and this is a bit of a blocker.

**Comment by StateBarofArizona** [comment]
Agreed that this is a HUGE bug in the widget.  The okta-sign-in.min.css trashes the CSS in my site no matter where I load it.

**Comment by sasso** [comment]
@omgitstom any updates?

**Comment by mraible** [comment]
@sasso I tested a branch of the widget today that has this fixed. Not sure when it will be released, but hopefully soon.

**Comment by scot1289** [comment]
Just signed up for Okta also and this is very annoying for my site also and is a blocker.

**Comment by sasso** [comment]
It's pretty disappointing that Okta is even working on other features and bugfixes as this is a complete blocker for anyone using this widget... 10 months from when this was first reported and still no fix (it's only css) 😔

**Comment by nilchaos87** [comment]
I would suggest [scope-css](https://www.npmjs.com/package/scope-css) as a workaround for anyone who's blocked. (Personally, I created a Webpack loader to roll it into my build process.)

**Comment by therealnicksaunders** [comment]
I would suggest scope-css as a workaround for anyone who's blocked. (Personally, I created a Webpack loader to roll it into my build process.)

**Comment by lboyette-okta** [comment]
@sasso @mraible The fixed version (2.1.0) has been published to npm.

**Comment by mraible** [comment]
Also available on CDN at http://cdn.jsdelivr.net/npm/@okta/okta-signin-widget@2.1.0/dist/js/okta-sign-in.min.js

**Comment by StateBarofArizona** [comment]
What is the status on the fix to 2.1.0 to correct the missing checkbox images?

**Comment by mraible** [comment]
@StateBarofArizona I've created a PR to fix this at https://github.com/okta/okta-signin-widget/pull/248. Trying to push it through this week.

**Comment by therealnicksaunders** [comment]
At the moment, I am using the sign-in widget @ ^1.13.0. Sadly the CSS issues have prevented me from directly including the stylesheet in my HTML document; instead, I have to pipe it through my build process which scopes the selectors to the element in which the widget is rendered and also corrects the checkbox image paths apparently fixed in the as-of-yet-unmerged PR #248.

I attempted to upgrade to 2.1.0 and of course the checkbox images are still broken. I am going to second @StateBarofArizona and suggest that @mraible's work really needs to be merged ASAP because I am *sure* you don't want clients having to implement this patch in a build process like I am doing.

Furthermore, I am going to ask @lboyette-okta to take another look at the selector scoping implementation. It looks like you guys have assigned an ID to the widget element and are using ID selectors, but this gives your CSS a high degree of specificity that still clobbers any styles that we try to apply to elements within the sign-in widget. Would you please apply a class like ```.okta-signin-widget``` instead of an ID like ```#okta-signin-widget```.

I have had two different colleagues ask me about the wacky-looking build steps that I have added to resolve these issues, and, frankly, it's embarrassing. I can't believe these would take more than a day to resolve fully, let alone 10 months!

**Comment by santhoshbalakrishnan** [comment]
@therealnicksaunders @StateBarofArizona  
ℹ️ The checkbox fix is in with https://github.com/okta/okta-signin-widget/pull/284

**Comment by rchild-okta** [comment]
Closing - fix for the main issue is in 2.1.0, and #284 is in master (will be in the next release).

**Comment by nilchaos87** [comment]
@rchild-okta I would like to reiterate that using ID selectors as a fix for this issue is problematic because it makes customizing the appearance of the sign-in widget difficult by creating a high degree of specificity in the selectors in the default stylesheet. In other words, our designer has difficulty overriding the default styles because the browser thinks the defaults are more important than his customizations. Is there any chance you guys can simply use a class instead of an ID?

**Comment by therealnicksaunders** [comment]
@rchild-okta I would like to reiterate that using ID selectors as a fix for this issue is problematic because it makes customizing the appearance of the sign-in widget difficult by creating a high degree of specificity in the selectors in the default stylesheet. In other words, our designer has difficulty overriding the default styles because the browser thinks the defaults are more important than his customizations. Is there any chance you guys can simply use a class instead of an ID?

**Comment by rchild-okta** [comment]
@therealnicksaunders mind opening another github issue for that? It's something we're looking to fix, but IIRC is a bit involved - we use an internal library for most of our components, and needed that extra specificity to workaround that implementation. We've been cleaning it up internally (it might already be at a point where we can swap it out), but requires some investigation.
