### ISSUE TITLE
widget breaks on single page apps

### ISSUE THREAD

**Issue by ajstocchetti** [okta/okta-signin-widget#168]
I'm trying to use the sign in widget on a SPA (using react). The issue is when you log out, then go back to the login page, the widget fails to load with error `Backbone.history has already been started`. With a single page app, the backbone process from the initial login is still active even after the user logs out. It would be great if there were some way to prevent this error: https://github.com/okta/okta-signin-widget/blob/master/node_modules/%40okta/courage/src/vendor/lib/backbone-1.2.1.js#L1606

**Comment by joelfranusic-okta** [comment]
Hi @ajstocchetti to avoid this error, I suggest using "show/hide" on the element containing the Okta Sign-In Widget.

**Comment by asharma93** [comment]
Alternatively, you can access Backbone from the window and call 'window.Backbone.history.stop()'.

**Comment by rchild-okta** [comment]
Tagged with "enhancement" - we do have a pending PR to add this explicitly to the widget [here](https://github.com/okta/okta-signin-widget/pull/136), but need a little more work before we merge it in.

**Comment by lawrencetvo** [comment]
+1 Also in the same boat with my application.

**Comment by kimu** [comment]
The problem with the solution suggested by @joelfranusic-okta is that it doesn't reset the widget.
I have the same issue, but luckily I am not developing a single page app, so I can reload the page, but this is terrible for UX. Having ajax calls in the background to validate the token I would like to be able to just reset the widget instead of reloading the page if an ajax call return an error. 

Also @asharma93 suggestion would work only if you are not using Backbone in your app. If you are developing a SPI with Backbone using history to register user interactions, calling `window.Backbone.history.stop()` would break your app.

@ajstocchetti the only suggestion I can give you is to put the widget in a iframe. maybe inside a dialog and let it have a life of its own, reloading the iframe to reset the widget if you need to.

This is quite an issue IMO. 👍  to resolve it quickly.

**Comment by rchild-okta** [comment]
PR to add show, hide and remove functions is here: https://github.com/okta/okta-signin-widget/pull/201. It still won't help in the case that @kimu mentioned - I've split that off into this issue: https://github.com/okta/okta-signin-widget/issues/202.

**Comment by lboyette-okta** [comment]
This is resolved by #201 and will be in the next release.
