### ISSUE TITLE
Error: undefined:5:49: missing '}' with Angular

### ISSUE THREAD

**Issue by mraible** [okta/okta-signin-widget#2138]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

If I include the Sign-In Widget's CSS in Angular's `angular.json`, there's an error when compiling and the app fails to start.

```json
"styles": [
  "src/styles.css",
  "node_modules/@okta/okta-signin-widget/dist/css/okta-sign-in.min.css",
  "node_modules/semantic-ui-css/semantic.min.css"
],
```

Error is:

```
Error: undefined:5:49: missing '}'
```

A workaround is to put the stylesheet reference in `src/index.html` instead. 

```html
<link href="https://global.oktacdn.com/okta-signin-widget/5.9.2/css/okta-sign-in.min.css" type="text/css" rel="stylesheet"/>
```

However, then you have to update the version manually (when dependabot creates updates to `package.json`). It also results in a warning (that doesn't seem to affect anything).

```
Warning: Unable to locate stylesheet: /Users/mraible/dev/okta-samples/okta-angular-sample/https:/global.oktacdn.com/okta-signin-widget/5.9.2/css/okta-sign-in.min.css
```

### Expected behavior

There should be no warning and everything should work.

### What went wrong?

I posted this in Slack and @jmelberg-okta said this is an issue with cssnano. https://github.com/cssnano/cssnano/issues/1105

I'm logging it here for more visibility and in hopes that it'll be fixed.

### Steps to reproduce

```
git clone https://github.com/okta-samples/okta-angular-sample.git
```

Then, change `angular.json` to reference the stylesheet as noted above and remove the reference from `src/index.html`. Run `npm start`. 

### Your environment

  - Okta Sign-In Widget Version: 5.9.2
  - Browser: Chrome 92
  - OS: Mac
  - Language: English

**Comment by shuowu** [comment]
Internal Ref: OKTA-418884

**Comment by naticaceres** [comment]
The logging in my project failed builds where I get this error points to this particular line in:
`https://global.oktacdn.com/okta-signin-widget/5.9.4/css/okta-sign-in.min.css` (and in the same file from my local instalation in node_modules for my project)

> @use "common/mixins"

which appears to be a scss rule, and doesn't seems to be valid css.
since the okta-sign-in.min.css is a css file, it expects it to be valid css, but when running validation, it isn't.

commenting it out on my local version of the file gets the problem fixed for me and doesn't seem to impact on the looks of the components I am using, but I whish we could take it directly from the url or the node package dependency instead.

is there any fix in sight?

otherwise, can I push a pull request with this change getting rid of those @use? I don't think they are doing anything in those css files not being valid css, unless I am missing something in the way you guys use those css files.

**Comment by naticaceres** [comment]
I created a [fork](https://github.com/naticaceres/okta-signin-widget) and fixed the problem for you.
looks like node-sass -deprecated- is no longer doing its job and compiling rules such as @use.
By installing dart sass and using the recommended grunt-sass configuration for it, it works as a charm.

also, the @use routes seemed to be broken.

I can't create a Pull Request for this repository. if you are willing to grant me the permissions needed, I'd love to collaborate.
Otherwise, here are my changes for you to check.
https://github.com/okta/okta-signin-widget/compare/master...50f6e99a524f53ae0d94e38b541642fafbf2c190

**Comment by mraible** [comment]
This seems to still be an issue. I tried it today with the latest versions and it still happens. What version of the Sign-In Widget is this fix targeted for?
