### ISSUE TITLE
Browserify Error: Cannot find module './View' from '/private/tmp/okta_signing-widget_pb/node_modules/@okta/okta-signin-widget/dist/js'

### ISSUE THREAD

**Issue by bsergean** [okta/okta-signin-widget#221]
(I love this sign in widget, it's quite simple to integrate; my only mistake was that I was using an HTTP connection instead of https and I was having weird errors.)

Here's a simple repro case.

```
$ cd /tmp/okta_signing-widget_pb
okta_signing-widget_pb$ ls
node_modules	package.json	repro.js
okta_signing-widget_pb$ cat package.json 
{
  "dependencies": {
    "@okta/okta-signin-widget": "^1.11.0"
  },
  "devDependencies": {
    "browserify": "^14.3.0"
  }
}
okta_signing-widget_pb$ cat repro.js 
var OktaSignIn = require('@okta/okta-signin-widget')
```

Now If I try to run browserify I get this error:

```
./node_modules/.bin/browserify repro.js 
Error: Cannot find module './View' from '/private/tmp/okta_signing-widget_pb/node_modules/@okta/okta-signin-widget/dist/js'
    at /private/tmp/okta_signing-widget_pb/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/private/tmp/okta_signing-widget_pb/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/private/tmp/okta_signing-widget_pb/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /private/tmp/okta_signing-widget_pb/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:114:15)
```

**Comment by manueltanzi-okta** [comment]
Hi @bsergean !

The problem is that browserify  attempts to resolve paths in require() calls in the already bundled okta-signin-widget, while it should ignore them since the okta-sign-in.entry.js is a standalone file and doesn't need the external modules, they are already bundled in the same file.

This is a browserify bug, it also happens when you try to require another file bundled by browserify (see https://github.com/substack/node-browserify/pull/1151).

A solution to this is to not parse the required okta-signin-widget.
You can use this code to do that:
`browserify --noparse=$PWD/node_modules/@okta/okta-signin-widget/dist/js/okta-sign-in.entry.js repro.js `
