### ISSUE TITLE
Showing the widget after logout doesn't work in an Angular app

### ISSUE THREAD

**Issue by mraible** [okta/okta-signin-widget#247]
Noted in [this blog post](https://developer.okta.com/blog/2017/03/27/angular-okta-sign-in-widget) from March.

I have a "logout" button that calls the following logout() method, but nothing happens on my screen. If I refresh my browser, I'm logged out.

```typescript
  showLogin() {
    this.oktaSignIn.renderEl({el: '#okta-login-container'}, (response) => {
      if (response.status === 'SUCCESS') {
        this.user = response.claims.email;
      }
    });
  }

  ngOnInit() {
    this.oktaSignIn.session.get((response) => {
      if (response.status !== 'INACTIVE') {
        this.user = response.login;
      } else {
        this.showLogin();
      }
    });
  }

  logout() {
    this.oktaSignIn.signOut(() => {
      this.showLogin();
      this.user = undefined;
    });
  }
```

Note that Lee was able to use `Backbone.history.stop()` in his [React example](https://developer.okta.com/blog/2017/03/30/react-okta-sign-in-widget). This does not work when using Angular.

**Comment by santhoshbalakrishnan** [comment]
@mraible I was able to get this working by changing your code a bit:

```
logout() {
    this.oktaSignIn.signOut(() => {
      // Set user to undefined first so that the view is updated
      this.user = undefined;

      // Manually let angular know that model changed
      this.changeDetectorRef.detectChanges();

      // An instance of the widget has already been rendered. Remove existing sign in instance.
      this.oktaSignIn.remove();

      this.showLogin();
    });
  }
```

One of the reasons the sign in widget did not render is that, angular did not know about the model change and the view did not update because of that. Since there is no container at that point for the widget to load, it did not load at all. Refer to screenshot below. At the point where the user is undefined, the view still stays at the "logged-in" state.

<img width="1868" alt="screen shot 2017-08-03 at 2 29 11 pm" src="https://user-images.githubusercontent.com/24683447/28944743-828d43a2-7858-11e7-991b-9ce55918ba62.png">

What I did was to manually trigger change detection in angular and also removed existing instance of Sign-In widget since there is one rendered already and was not removed. Also, ```backbone.history.stop``` is triggered ```remove``` is called. Hope this solves your problem!

**Comment by mraible** [comment]
@santhoshbalakrishnan @jmelberg-okta I created a new application today that uses the sign-in widget. Unfortunately, I'm still having issues with signout. It's likely not the widget's fault, but Angular and routing. If you have time, please take a look at [okta-kotlin-typescript-notes-example](https://github.com/oktadeveloper/okta-kotlin-typescript-notes-example). I'll be using this code in an article I'm writing tonight.

The logout issue I'm experiencing is in [app.component.ts#L27](https://github.com/oktadeveloper/okta-kotlin-typescript-notes-example/blob/master/client/src/app/app.component.ts#L27).

To login to this app, you can ping me on HipChat and I can provide credentials, or you can change it to match your own. You'll need to change `application.properties` in the server and `okta.service.ts` on the client.
