### ISSUE TITLE
Okta SignIn Widget is rendering, but empty

### ISSUE THREAD

**Issue by rw3iss** [okta/okta-signin-widget#278]
I am initializing the code according the React example, and the widget shows up, but has no fields or text. Does anyone why this could be? No errors are thrown. Please see the code and screenshot below (dev-id and clientId are hidden for security).

```
this.loginWidget = new OktaSignIn({
    baseUrl: 'https://dev-<dev-id>.oktapreview.com',
    clientId: '<clientId>',
    redirectUri: 'http://localhost:8080/',
    authParams: {
        responseType: 'id_token'
    }
});

console.log("rendering login widget", this.loginWidget, this.loginContainer);
this.loginWidget.renderEl({el: this.loginContainer},
    (response) => {
        console.log("Signin response", response);
        //this.setState({user: response.claims.email});
    },
    (err) => {
        console.log(err);
    }
); 
```

In render():

`                        <div ref={(div) => {this.loginContainer = div; }} ></div>`

![screen shot 2017-08-10 at 13 51 45](https://user-images.githubusercontent.com/372120/29184197-663b80da-7dd3-11e7-9f82-1f5464b40cf1.png)

The code it renders is also "empty", ie:

```
<div>
    <div data-se="auth-container" id="okta-sign-in" class="auth-container main-container no-beacon">
        <div class="okta-sign-in-header auth-header">
            <div data-type="beacon-container" class="beacon-container"></div>
        </div>
        <div class="auth-content">
            <div class="auth-content-inner"></div>
        </div>
    </div>
</div>
```

**Comment by rw3iss** [comment]
I was able to get around it by downgrading to signin widget v 1.9.0, and also changing the "main" property of the package's package.json to "main": "./dist/js/okta-sign-in-no-jquery.js"

**Comment by epiales** [comment]
Thanks @rw3iss, was having this same problem with 2.1.0 and switching to the no-jquery bundle fixed the issue for me.

```es6
import OktaSignIn from '@okta/okta-signin-widget/dist/js/okta-sign-in-no-jquery';
```

**Comment by santhoshbalakrishnan** [comment]
@rw3iss @epiales Can you please check if this is still the case with 2.5.0?

The latest release of the widget (2.5.0) fixes this issue:

```npm install @okta/okta-signin-widget@2.5.0 --save```

You can to import the widget directly:

```import * as OktaSignIn from '@okta/okta-signin-widget'```

Ref: https://github.com/okta/okta-signin-widget/issues/320

**Comment by epiales** [comment]
@santhoshbalakrishnan I tested with 2.5.0 and can confirm it worked for me 👍

**Comment by quirogamauricio** [comment]
This is still happening on version `2.10.0`. I can't use `2.5.0` due to the `$.cookie is not a function` error.
I tried the approach mentioned above, which is importing the widget this way:

`import * as OktaSignIn from '@okta/okta-signin-widget/dist/js/okta-sign-in-no-jquery'`

I can leave it like this by now, but it would be great it you could look into this problem.
If you need more information i'll be happy to provide it.

**Comment by FelixFriedman** [comment]
This is still a problem in 2.19.0

**Comment by tcarrio** [comment]
Just encountered this issue as well. Will report my finding using some of the suggestions here.

**Comment by tcarrio** [comment]
Just a preliminary, this issue was encountered with our build configurations with options like optimized builds and others changed. It could be something in the following that causes the issue:

```
"optimization": true,
"outputHashing": "all",
"sourceMap": false,
"extractCss": true,
"namedChunks": false,
"aot": true,
"extractLicenses": true,
"vendorChunk": false,
"buildOptimizer": true,
"budgets": [
{
    "type": "initial",
    "maximumWarning": "2mb",
    "maximumError": "5mb"
}
]
```

It seems to be a bug related to something in our build configuration. But once again, will report more with my findings.

**Comment by JonathanDX** [comment]
@tcarrio I had the same issue. I found turning off build optimizer fixed the rendering issue. 

Obviously this is not ideal..

**Comment by tcarrio** [comment]
I found the same. Really not ideal.

**Comment by sparachi** [comment]
https://github.com/okta/okta-signin-widget/issues/515
I'm working with 3.2.0 version and had to struggle for a day to figure out why the widget was not rendering. There was just one horizontal line and no console errors. When I moved the
this.widgetObject.renderEl() to ngAfterViewInit instead of ngOninit did the trick and it started to load. I did not turn off the build optimizer flag.

**Comment by tcarrio** [comment]
Would be very exciting if that consistently fixes this for everyone. Thanks for the heads up @sparachi
