### ISSUE TITLE
context controller is null

### ISSUE THREAD

**Issue by Jorden-V** [okta/okta-signin-widget#3240]
### Describe the bug

Upgrading to OIE and the latest sign in widget has changed behaviours with context controllers for post render.

context.controller = null

### Reproduction Steps

Example 1:
1. Login screen, controller = primary-auth
2. Forgot password screen, controller = forgot-password
3. Submit email account for recovery, controller = null on page to send email or sms for recovery.

Example 2:
1. Login screen, controller = primary-auth
2. Create an account screen, controller = registration
3. Submit to enroll page, controller = enroll-choices
4. Page to enter mfa code or enroll, controller = null

Example 3:
This one is a slightly different bug but related, if you enable 'Show password field on the first page of the enrollment form' in the console, the registration controller page goes from `registration` to `null`.

### SDK Versions

https://global.oktacdn.com/okta-signin-widget/7.6.0/css/okta-sign-in.min.css

**Comment by jaredperreault-okta** [comment]
I assume you're talking about the `afterRender` event handler? I'm not sure of the exact reasons, however the `afterRender` context provides a mapping between classic (authn) controllers and OIE views (the OIE widget is built on a single controller). It seems like in some cases there isn't a mapping. I'd suggest keying off of `context.formName` instead or utilize the `before()/after()` hooks, rather than `afterRender`

(Note: the OIE widget is a complete re-write)

Do you mind explaining your use case for the controller names?

**Comment by SilverCory** [comment]
Thanks for the response @jaredperreault-okta we're using the `afterRender` event handler yes.

We use `afterRender` for a tracking and page customisation. We also use `afterError` for tracking.

We've been using the controller names in classic to add/change elements on the page via JS (IE custom back buttons). We're currently in the process of upgrading the widget to be compatible with OIE.

**Comment by SilverCory** [comment]
#2269

**Comment by jaredperreault-okta** [comment]
The OIE widget is a complete re-write, so the controller names from the classic widget won't apply in many cases. I suggest keying off of the `context.formName` property instead
