### ISSUE TITLE
404 Error when session.get returns no active session

### ISSUE THREAD

**Issue by mlawson3691** [okta/okta-signin-widget#328]
The README says {status: inactive} will be returned if session.get returns no/inactive session. The request looks like it's calling the Session API, and those docs say a 404 is returned in this case.

Is it possible to return a value as described in the README here so that my app doesn't throw a 404 error every time an un-authenticated user lands on the page?

**Comment by jpotterpath** [comment]
+1
The biggest issue in my opinion is that it makes the user think there is an issue with the application rather than confirmation that a session is inactive. 

The issue is pretty consistent across browsers as well. I personally tested this with Chrome, Firefox, Opera, and Safari. Firefox gets by without giving the user feedback of the 404 .. maybe cause really there is a response there for {status: "INACTIVE"}

Either way. Here is a copy of an example to recreate this issue: 
```javascript
var oktaSignIn = new OktaSignIn({
    baseUrl: 'https://dev-XXXXXX.oktapreview.com'
});

oktaSignIn.session.get(function (res) {
    console.log('oktaSignIn.session.get', res);
});
```

**Comment by jpotterpath** [comment]
Would y'all be able to respond with a 401 Unauthorized instead?

**Comment by robertjd** [comment]
Hi @mlawson3691 , thanks for the question.  Since our API will always return an HTTP error code if there is no session you will always see that HTTP error in your browser's network log.  Is your concern about the end-user seeing this message?  Or do you have come kind of global HTTP error handler that is getting triggerd?

@jpotterpath changing it to 401 might make more sense semantically, but you'd still see it as in error in the network log.

**Comment by jpotterpath** [comment]
@robertjd a 401 is an error I'd prefer to display as it usually is accompanied with a bit of feedback of '401 (Unauthorized)'.

Here is an example from my experience with API's and authentication, at least with passing an API key to do so. Say I try and access the Marvel API with a bad API key: 
http://gateway.marvel.com/v1/public/characters?nameStartsWith=gambit&offset=0&limit=10&apikey=AHAHAHYOUDIDNTSAYTHEMAGICWORD

They return a 401. Feels good and like you mention semantically makes sense. The 404 immediately sent me on a path of looking for what I had configured wrong, or implemented improperly. 

Thank you for your response!

**Comment by robertjd** [comment]
I agree, 401 is more descriptive.  Changing this now would be a breaking change on v1 of the API, but I've forwarded this request along.  Thanks for the feedback!

**Comment by jpotterpath** [comment]
Word up! Thanks again @robertjd
