### ISSUE TITLE
Forgot password does not validate when submitting by pressing Enter key

### ISSUE THREAD

**Issue by loqtor** [okta/okta-signin-widget#393]
Hi guys,

The widget does not validate when the user submits the Forgot Password form by pressing enter.

Steps:

1 - Get to where the widget is (probably the Login Page of your site) and click on the "Forgot password" link.
2 - On the next screen/widget state, enter anything but an email (i.e.: "aaaaaa") in the email field.
3 - Press enter.

**Expected**: An error should be shown and the form should not be submitted.
**Actual**: No error is shown and form is submitted with a value that is not an email.

I'm using version 2.6 of the widget.

Let me know if you need more information. Sorry if it's a duplicate, but I could not find another one related or similar.

Cheers!

**Comment by santhoshbalakrishnan** [comment]
@loqtor That's because we accept either an email or an username. Having that field as an email is not required.

We have a placeholder that says "email or username".

Screenshot:

<img width="443" alt="screen shot 2018-02-07 at 3 35 30 pm" src="https://user-images.githubusercontent.com/24683447/35948030-68536d58-0c1f-11e8-9aa9-f8d6df6fc3b8.png">

**Comment by loqtor** [comment]
Thanks, @santhoshbalakrishnan. Makes sense.

If I require that to be an email, is there an option in the config to force the form to only accept valid emails for submission?
Otherwise, is there another way you'd recommend for me to change this behaviour and force an email validation?

Cheers!
